### ISSUE TITLE
unable to build on MacOS

### ISSUE THREAD

**Issue by etiennedemoulin** [Cycling74/rnbo.oscquery.runner#1]
Trying to build the query on MacOS, but I don't find my way because I can't fidn RNBO source code on CMakeLists.txt : 
`#find RNBO
find_path(
	RNBO_DIR
	NAMES "RNBO.cpp"
	PATHS
		${CMAKE_CURRENT_SOURCE_DIR}/../../src/cpp/
		${CMAKE_CURRENT_SOURCE_DIR}/../rnbo/
	NO_DEFAULT_PATH
	DOC "Location of the RNBO C++ source code"
)`
Is this code somewhere ?

Best

Etienne

**Comment by x37v** [comment]
Ahh yeah, I just updated the README with the details you should need: https://github.com/Cycling74/rnbo.oscquery.runner#building

**Comment by etiennedemoulin** [comment]
i would suggest : cmake .. -DRNBO_DIR=/Applications/Max.app/Contents/Resources/C74/packages/RNBO/source/rnbo && make -j8
thanks !

**Comment by x37v** [comment]
ahh yes, that makes sense considering it is bundled with max.. once you do an update via the package manager, you'll want to change to the path in the README, though it makes sense that the README should have both.
